# k8s_test/step24_microservice_helm/Chart.yaml

apiVersion: v2 
name: msa-platform
description: index + market + post
type: application
version: 0.1.3
appVersion: "1.0.1"

dependencies:
  - name: index-app
    version: "0.1.1"
    repository: "file://charts/index"
    condition: index-app.enabled
  
  - name: market-app
    version: "0.1.2"
    repository: "file://charts/market"
    condition: market-app.enabled
  
  - name: post-app
    version: "0.1.2"
    repository: "file://charts/post"
    condition: post-app.enabled
  