# git_repo/step24_microservice_helm/charts/market/templates/deploy.yaml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: market-app
  template:
    metadata:
      labels:
        app: market-app
    spec:
      containers:
      - name: market-ctn
        image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:
          limits:
            cpu: "200m"
            memory: "64Mi"
        startupProbe:
          httpGet:
            path: /health
            port: {{ .Values.containerPort }}
          periodSecond: 10
          failureThreshold: 15
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 0
          periodSeconds: 10
        readinessProbe:
          httpGet: 
            path: /health
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 0
          periodSeconds: 5